version: '3.7'

services:    
  main:
    image: ghcr.io/processone/ejabberd
    container_name: ejabberd-main
    ports:
      - "5222:5222"
      - "5269:5269"
      - "80:5280"
      - "5443:5443"
    env_file:
      - ./ejabberd/env/.env
      - ./ejabberd/env/module.env
    volumes:
      - ./ejabberd/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
      - ./ejabberd/database:/opt/ejabberd/database
      - ./ejabberd/letsencrypt/live/chat.demo.edyou.io:/etc/letsencrypt/live/chat.demo.edyou.io
    environment:
      - ERLANG_NODE_ARG=ejabberd@main
      - ERLANG_COOKIE=ejabberdcookie
      - CTL_ON_CREATE=
          register admin chat.demo.edyou.io admin ;
          register samee chat.demo.edyou.io samee ;
          register hasnat chat.demo.edyou.io hasnat ;
          register nabeel chat.demo.edyou.io nabeel ;
          register faisal chat.demo.edyou.io faisal
      - CTL_ON_START=registered_users chat.demo.edyou.io ;
        status
